- id: evening-lights
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
    service: switch.turn_on
    entity_id: switch.shelly_shsw_pm_766cbe # entrance light
    
- id: evening-windows
  trigger:
    platform: sun
    event: sunset
    offset: '03:00:00'
  action:
    service: cover.close_cover
    entity_id: 
      - cover.shelly_shsw_25_b92fd1
      - cover.shelly_shsw_25_68c63af981be

- id: midnight
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.shelly_shsw_pm_766cbe
        - switch.shelly_shsw_25_68c63af91b61_1 # living room lights
        - switch.shelly_shsw_25_68c63af91b61_2 # living room peripheral
    - service: cover.close_cover
      entity_id: 
        - cover.shelly_shsw_25_b92fd1
        - cover.shelly_shsw_25_68c63af981be

- id: shabbat-starts
  trigger:
    platform: state
    entity_id: group.shabbat_timers_in_effect
    from: 'off'
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.shelly_shsw_pm_766cbe
        - switch.shelly_shsw_pm_766477 # master bedroom light
        - switch.shelly_shsw_25_68c63af91b61_1
        - switch.shelly_shsw_25_68c63af91b61_2
    - service: cover.open_cover
      entity_id: 
        - cover.shelly_shsw_25_b92fd1
        - cover.shelly_shsw_25_68c63af981be
    - service: media_player.turn_off
      entity_id: 
        - media_player.nestmini9591
        - media_player.amit_s_echo_dot
      
- id: shabbat-master-bedroom-on
  trigger:
    platform: template
    value_template: "{{ states('input_number.shabbat_master_bedroom_lights') | int | bitwise_and(2 ** (states('sensor.time').split(':')[0] | int)) > 0}}"
  condition:
    - condition: state
      entity_id: switch.shelly_shsw_pm_766477
      state: 'off'
    - condition: state
      entity_id: group.shabbat_timers_in_effect_master_bedroom
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.shelly_shsw_pm_766477

- id: shabbat-master-bedroom-off
  trigger:
    platform: template
    value_template: "{{ states('input_number.shabbat_master_bedroom_lights') | int | bitwise_and(2 ** (states('sensor.time').split(':')[0] | int)) == 0}}"
  condition:
    - condition: state
      entity_id: switch.shelly_shsw_pm_766477
      state: 'on'
    - condition: state
      entity_id: group.shabbat_timers_in_effect_master_bedroom
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.shelly_shsw_pm_766477

- id: shabbat-main-floor-on
  trigger:
    platform: template
    value_template: "{{ states('input_number.shabbat_main_floor') | int | bitwise_and(2 ** (states('sensor.time').split(':')[0] | int)) > 0}}"
  condition:
    - condition: state
      entity_id: switch.shelly_shsw_pm_766cbe
      state: 'off'
    - condition: state
      entity_id: group.shabbat_timers_in_effect_main_floor
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.shelly_shsw_pm_766cbe
        - switch.shelly_shsw_25_68c63af91b61_1
    - service: cover.open_cover
      entity_id: 
        - cover.shelly_shsw_25_b92fd1
        - cover.shelly_shsw_25_68c63af981be
- id: shabbat-main-floor-off
  trigger:
    platform: template
    value_template: "{{ states('input_number.shabbat_main_floor') | int | bitwise_and(2 ** (states('sensor.time').split(':')[0] | int)) == 0}}"
  condition:
    - condition: state
      entity_id: switch.shelly_shsw_pm_766cbe
      state: 'on'
    - condition: state
      entity_id: group.shabbat_timers_in_effect_main_floor
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.shelly_shsw_pm_766cbe
        - switch.shelly_shsw_25_68c63af91b61_1
    - service: cover.close_cover
      entity_id: 
        - cover.shelly_shsw_25_b92fd1
        - cover.shelly_shsw_25_68c63af981be
