- id: evening-lights
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
    service: switch.turn_on
    entity_id: switch.shelly_shsw_pm_766cbe # entrance light
    
- id: evening-windows
  trigger:
    platform: sun
    event: sunset
    offset: '00:45:00'
  action:
    service: cover.close_cover
    entity_id: cover.shelly_shsw_25_b92fd1

- id: midnight
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.shelly_shsw_pm_766cbe
    - service: cover.close_cover
      entity_id: cover.shelly_shsw_25_b92fd1

- id: shabbat-starts
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.shabbat_timers
      state: 'on'  
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.shelly_shsw_pm_766cbe
        - switch.shelly_shsw_pm_766477 # master bedroom light
    - service: cover.open_cover
      entity_id: cover.shelly_shsw_25_b92fd1
    - service: media_player.turn_off
      entity_id: 
        - media_player.nestmini9591
        - media_player.amit_s_echo_dot
      
- id: shabbat-night
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.shabbat_night_master_bedroom', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: sensor.shabbat_timers_in_effect
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.shelly_shsw_pm_766477

- id: shabbat-morning
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.shabbat_morning_public', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: sensor.shabbat_timers_in_effect
      state: 'on' 
  action:
    - service: switch.turn_on
      entity_id: switch.shelly_shsw_pm_766cbe
    - service: cover.open_cover
      entity_id: cover.shelly_shsw_25_b92fd1      
    
- id: shabbat-morning-master-bedroom
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.shabbat_morning_master', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: sensor.shabbat_timers_in_effect
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.shelly_shsw_pm_766477
      
- id: shabbat-nap-master-bedroom
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.shabbat_nap_master', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: sensor.shabbat_timers_in_effect
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.shelly_shsw_pm_766477
      
- id: shabbat-afternoon-master-bedroom
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.shabbat_afternoon_master', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: sensor.shabbat_timers_in_effect
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.shelly_shsw_pm_766477
