default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml

shelly:
  host_ip: 10.100.102.240

jewish_calendar:

input_boolean:
  shabbat_timers:
  shabbat_timers_main_floor:
  shabbat_timers_master_bedroom:
  shabbat_timers_reut:
  shabbat_timers_shaked:
  shabbat_timers_roei:

input_number:
  shabbat_master_bedroom_lights:
    min: 0
    max: 281474976710655
  shabbat_master_bedroom_ac:
    min: 0
    max: 281474976710655
  shabbat_main_floor:
    min: 0
    max: 281474976710655
  shabbat_hot_plate:
    min: 0
    max: 281474976710655
  shabbat_reut_ac:
    min: 0
    max: 281474976710655
  shabbat_shaked_ac:
    min: 0
    max: 281474976710655
  shabbat_roei_ac:
    min: 0
    max: 281474976710655

sensor:
  - platform: rest
    name: shelly_9555ae_tmp
    resource: !secret shelly_9555ae_rest
    value_template: '{{ value_json.data.device_status.tmp.value }}'
    device_class: temperature
    unit_of_measurement: '°C'
    scan_interval: 600
  - platform: rest
    name: shelly_9555ae_hum
    resource: !secret shelly_9555ae_rest
    value_template: '{{ value_json.data.device_status.hum.value }}'
    device_class: humidity
    unit_of_measurement: '%'
    scan_interval: 600

tts:
  - platform: google_translate
