default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shelly:
  host_ip: 10.100.102.240

jewish_calendar:

input_boolean:
  shabbat_timers:
    
input_datetime:
  shabbat_night_master_bedroom:
    has_time: true
  shabbat_morning_public:
    has_time: true
  shabbat_morning_master:
    has_time: true
  shabbat_nap_master:
    has_time: true
  shabbat_afternoon_master:
    has_time: true

sensor:
  - platform: rest
    name: shelly_9555ae_tmp
    resource: !secret shelly_9555ae_rest
    value_template: '{{ value_json.data.device_status.tmp.value }}'
    device_class: temperature
    unit_of_measurement: '°C'
    scan_interval: 600
  - platform: rest
    name: shelly_9555ae_hum
    resource: !secret shelly_9555ae_rest
    value_template: '{{ value_json.data.device_status.hum.value }}'
    device_class: humidity
    unit_of_measurement: '%'
    scan_interval: 600

tts:
  - platform: google_translate
