default_config:

http:
  base_url: amitf.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shelly:

jewish_calendar:

sensor:
  - platform: time_date
    display_options:
      - 'date'
      - 'time'
      - 'date_time'
      - 'time_date'

tts:
  - platform: google_translate
