default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shelly:
  host_ip: 10.100.102.240

jewish_calendar:

input_boolean:
  shabbat_timers:

input_number:
  shabbat_master_bedroom_lights:
    min: 0
    max: 16777215
  shabbat_main_floor:
    min: 0
    max: 16777215

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: rest
    name: shelly_9555ae_tmp
    resource: !secret shelly_9555ae_rest
    value_template: '{{ value_json.data.device_status.tmp.value }}'
    device_class: temperature
    unit_of_measurement: '°C'
    scan_interval: 600
  - platform: rest
    name: shelly_9555ae_hum
    resource: !secret shelly_9555ae_rest
    value_template: '{{ value_json.data.device_status.hum.value }}'
    device_class: humidity
    unit_of_measurement: '%'
    scan_interval: 600

tts:
  - platform: google_translate
