default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shelly:
  host_ip: 10.100.102.240

jewish_calendar:

input_boolean:
  shabbat_timers:
    
input_datetime:
  shabbat_night_master_bedroom:
    has_time: true
  shabbat_morning_public:
    has_time: true
  shabbat_morning_master:
    has_time: true
  shabbat_nap_master:
    has_time: true
  shabbat_afternoon_master:
    has_time: true

tts:
  - platform: google_translate
