- name: shabbat_main_floor_lights
  switch: group.shabbat_timers_in_effect_main_floor
  timer: shabbat_main_floor
  domain: switch
  entities:
    - entrance_lights
    - living_room_lights
    - living_room_peripheral_lights

- name: shabbat_main_floor_windows
  switch: group.shabbat_timers_in_effect_main_floor
  timer: shabbat_main_floor
  domain: cover
  entities:
    - living_room_windows
    - dinning_room_windows

- name: shabbat_hot_plate
  switch: group.shabbat_timers_in_effect_main_floor
  timer: shabbat_hot_plate
  domain: switch
  entities:
    - hot_plate

- name: shabbat_master_bedroom_lights
  switch: group.shabbat_timers_in_effect_master_bedroom
  timer: shabbat_master_bedroom_lights
  domain: switch
  entities:
    - master_bedroom_lights

- name: shabbat_master_bedroom_ac
  switch: group.shabbat_timers_in_effect_master_bedroom
  timer: shabbat_master_bedroom_ac
  domain: switch
  entities:
    - master_bedroom_ac

- name: shabbat_reut_ac
  switch: group.shabbat_timers_in_effect_reut
  timer: shabbat_reut_ac
  domain: switch
  entities:
    - reut_ac

- name: shabbat_shaked_ac
  switch: group.shabbat_timers_in_effect_shaked
  timer: shabbat_shaked_ac
  domain: switch
  entities:
    - shaked_ac

- name: shabbat_roei_ac
  switch: group.shabbat_timers_in_effect_roei
  timer: shabbat_roei_ac
  domain: switch
  entities:
    - roei_ac
