- name: shabbat_main_floor_lights
  switch: group.shabbat_timers_in_effect_main_floor
  timer: shabbat_main_floor
  domain: switch
  entities:
    - shelly_shsw_pm_766cbe
    - shelly_shsw_25_68c63af91b61_1
    - shelly_shsw_25_68c63af91b61_2

- name: shabbat_main_floor_windows
  switch: group.shabbat_timers_in_effect_main_floor
  timer: shabbat_main_floor
  domain: cover
  entities:
    - shelly_shsw_25_b92fd1
    - shelly_shsw_25_68c63af981be

- name: shabbat_hot_plate
  switch: group.shabbat_timers_in_effect_main_floor
  timer: shabbat_hot_plate
  domain: switch
  entities:
    - shelly_shsw_1_e09806958318

- name: shabbat_master_bedroom_lights
  switch: group.shabbat_timers_in_effect_master_bedroom
  timer: shabbat_master_bedroom_lights
  domain: switch
  entities:
    - shelly_shsw_pm_766477

- name: shabbat_master_bedroom_ac
  switch: group.shabbat_timers_in_effect_master_bedroom
  timer: shabbat_master_bedroom_ac
  domain: switch
  entities:
    - shelly_shsw_1_e098069513b6

- name: shabbat_reut_ac
  switch: group.shabbat_timers_in_effect_reut
  timer: shabbat_reut_ac
  domain: switch
  entities:
    - shelly_shsw_1_68c63afa10ab

- name: shabbat_shaked_ac
  switch: group.shabbat_timers_in_effect_shaked
  timer: shabbat_shaked_ac
  domain: switch
  entities:
    - shelly_shsw_1_68c63afa64e2

- name: shabbat_roei_ac
  switch: group.shabbat_timers_in_effect_roei
  timer: shabbat_roei_ac
  domain: switch
  entities:
    - shelly_shsw_1_e098069585b6
