title: Finkelstein
views:
  - title: Home
    path: default_view
    cards:
      - title: Scenes
        type: entities
        entities:
          - scene.shutdown_all
        show_header_toggle: false
      - title: Lights
        type: entities
        entities:
          - entity: switch.shelly_shsw_pm_766cbe
          - entity: switch.shelly_shsw_pm_766477
      - title: Windows
        type: entities
        entities:
          - entity: cover.shelly_shsw_25_b92fd1
      - title: Speakers
        type: entities
        entities:
          - entity: media_player.nestmini7196
          - entity: media_player.amit_s_echo_dot
  - title: Info
    path: info
    cards:
      - type: glance
        entities:
          - entity: sensor.date_time
        show_icon: false
        show_state: true
        show_name: false
      - type: weather-forecast
        entity: weather.home
      - type: shopping-list
        title: Shopping List
  - title: Shabbat
    path: shabbat
    cards:
      - entities:
          - entity: input_boolean.shabbat_timers
        title: Global Switch
        type: entities
      - entities:
          - entity: input_datetime.shabbat_morning_public
          - entity: input_datetime.shabbat_morning_master
          - entity: input_datetime.shabbat_nap_master
          - entity: input_datetime.shabbat_afternoon_master
        show_header_toggle: false
        title: Set Time
        type: entities
