title: Finkelstein
views:
  - cards:
      - entities:
          - entity: script.shutdown_all
        show_header_toggle: false
        title: Scenes
        type: entities
      - entities:
          - entity: switch.shelly_shsw_pm_766cbe
          - entity: switch.shelly_shsw_25_68c63af91b61_1
          - entity: switch.shelly_shsw_25_68c63af91b61_2
          - entity: switch.shelly_shsw_pm_766477
        title: Lights
        type: entities
      - entities:
          - entity: cover.shelly_shsw_25_b92fd1
          - entity: cover.shelly_shsw_25_68c63af981be
        title: Windows
        type: entities
      - entities:
          - entity: switch.shelly_shsw_1_e098069513b6
            name: Master
          - entity: switch.shelly_shsw_1_68c63afa10ab
            name: Reut
          - entity: switch.shelly_shsw_1_68c63afa64e2
            name: Shaked
          - entity: switch.shelly_shsw_1_e098069585b6
            name: Roei
        show_header_toggle: false
        title: A/C
        type: entities
      - entities:
          - entity: media_player.nestmini4522
        title: Speakers
        type: entities
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - entity: input_boolean.shabbat_timers
            icon: 'mdi:candle'
            name: Timers for Shabbat & Holiday
        title: Global Switch
        type: entities
      - entities:
          - entity: input_number.shabbat_main_floor
            name: Lights & Windows
          - entity: input_number.shabbat_hot_plate
            name: Hot Plate
        title: Main Floor
        toggle: input_boolean.shabbat_timers_main_floor
        type: 'custom:timer-24h-card'
      - entities:
          - entity: input_number.shabbat_master_bedroom_lights
            name: Lights
          - entity: input_number.shabbat_master_bedroom_ac
            name: A/C
        title: Master Bedroom
        toggle: input_boolean.shabbat_timers_master_bedroom
        type: 'custom:timer-24h-card'
      - entities:
          - entity: input_number.shabbat_reut_ac
            name: A/C
        title: Reut Bedroom
        toggle: input_boolean.shabbat_timers_reut
        type: 'custom:timer-24h-card'
      - entities:
          - entity: input_number.shabbat_shaked_ac
            name: A/C
        title: Shaked Bedroom
        toggle: input_boolean.shabbat_timers_shaked
        type: 'custom:timer-24h-card'
      - entities:
          - entity: input_number.shabbat_roei_ac
            name: A/C
        title: Roei Bedroom
        toggle: input_boolean.shabbat_timers_roei
        type: 'custom:timer-24h-card'
    path: Shabbat
    title: Shabbat
  - badges: []
    cards:
      - entity: weather.home
        type: weather-forecast
      - entity: sensor.shelly_9555ae_tmp
        graph: line
        name: Living Room Temperture
        type: sensor
      - entity: sensor.shelly_9555ae_hum
        graph: line
        name: Living Room Humidity
        type: sensor
    path: weather
    title: Weather
