- control: [binary_sensor.always_on]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.front_door_internal_lights
    - light.master_bedroom_toilet_light
    - light.guest_bathroom_light

- control: [binary_sensor.always_off]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.roei_main_lights
    - light.roei_peripheral_lights
    - light.reut_room_peripheral_lights
    - light.shaked_peripheral_lights
    - light.maayan_room_peripheral_lights
    - light.master_bedroom_light
    - light.attic_lights
    - light.attic_stairs_lights
    - light.coat_room_light
    - light.den_lights
    - light.den_desk_light
    - light.middle_floor_hallway_up_down
    - light.service_room_light
    - light.upper_floor_hallway_lights
    - light.upper_stairs_guiding_lights
    - light.upper_stairs_up_down_lights

- control: [binary_sensor.always_off]
  condition: [group.shabbat_timers_in_effect]
  action: switch
  entities:
    - switch.master_bathroom_toilet_outlet
    - switch.gas_water_heater

- control: [binary_sensor.always_off]
  condition: [group.shabbat_timers_in_effect]
  action: cover
  entities:
    - cover.roei_door
    - cover.shaked_door
    - cover.tv_room_door
    - cover.tv_room_window

- control: [binary_sensor.always_off]
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.den_ac
    - climate.service_room_ac
    - climate.tv_room

- control: [binary_sensor.shabbat_main_floor_lights]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.kitchen_main_light
    - light.kitchen_counter_lights
    - light.kitchen_spot_lights
    - light.living_room_main_lights
    - light.dining_room_main_light
    - light.family_room_main_light

- control: [binary_sensor.shabbat_main_floor_other_lights]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.family_room_peripheral_lights
    - light.family_room_up_down_lights
    - light.dining_room_upper_light
    - light.living_room_curtains_lights
    - light.living_room_peripheral_lights
    - light.living_room_up_down_lights
    - light.south_curtain_lights
    - light.guest_sink_light
    - light.lower_stairs_guiding_lights
    - light.lower_stairs_up_down_lights

- control: [binary_sensor.shabbat_front_yard_entrance_lights]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.front_yard_lights
    - light.surrounding_up_down_lights
    - light.entrance_light
    - light.external_stairs
    - light.front_fence
    - light.front_garden
    - light.tree_lights
    - light.external_up_down_lights
    - light.front_yard_up_down_light
    - light.roei_external_lights
    - light.shaked_external_lights

- control: [binary_sensor.shabbat_hot_plate]
  condition: [group.shabbat_timers_in_effect]
  action: switch
  entities:
    - switch.hot_plate

- control: [binary_sensor.shabbat_main_floor_blinds]
  condition: [group.shabbat_timers_in_effect]
  action: cover
  entities:
    - cover.kitchen_window
    - cover.living_room_door
    - cover.living_room_north
    - cover.living_room_west
    - cover.living_room_window

- control: [input_boolean.shabbat_shelter_lights]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities: [light.shelter_lights]

- control: [binary_sensor.shabbat_family_room_door]
  condition: [group.shabbat_timers_in_effect]
  action: cover
  entities:
    - cover.family_room_door

- control: [binary_sensor.shabbat_pergola_lights]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.pergola_lights
    - light.backyard_fence_lights
    - light.backyard_garden_lights

- control: [binary_sensor.shabbat_pergola_lights]
  condition: [group.shabbat_timers_in_effect]
  action: switch
  entities:
    - switch.pergola_kitchen_fan
    - switch.pergola_seating_fans

- control: [binary_sensor.shabbat_dishwasher]
  condition: [group.shabbat_timers_in_effect]
  action: switch
  entities:
    - switch.meat_dishwasher

- control: [binary_sensor.shabbat_living_room_ac]
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.living_room_ac

- control: [binary_sensor.shabbat_kitchen_ac]
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.kitchen_ac

- control: [binary_sensor.shabbat_family_room_ac]
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.family_room_ac

- control:
    - binary_sensor.shabbat_guest_room_lights
    - input_boolean.shabbat_timers_guest_room
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.guest_room_main_light
    - light.guest_room_peripheral_lights

- control:
    - binary_sensor.shabbat_guest_bathroom_lights
    - input_boolean.shabbat_timers_guest_room
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.guest_room_bathroom_lights

- control:
    - binary_sensor.shabbat_guest_room_ac
    - input_boolean.shabbat_timers_guest_room
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.guest_room_ac

- control: [binary_sensor.shabbat_front_yard_main_light]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.front_yard_main_light

- control: [binary_sensor.shabbat_front_yard_outlet_north]
  condition: [group.shabbat_timers_in_effect]
  action: switch
  entities:
    - switch.front_yard_outlet_n

- control: [binary_sensor.shabbat_front_yard_outlet_south]
  condition: [group.shabbat_timers_in_effect]
  action: switch
  entities:
    - switch.front_yard_outlet_s

- control:
    - binary_sensor.shabbat_master_bedroom_ac
    - input_boolean.shabbat_timers_master_bedroom
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.master_bedroom_ac

- control:
    - binary_sensor.shabbat_reut_ac
    - input_boolean.shabbat_timers_reut
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.reut_ac

- control:
    - binary_sensor.shabbat_shaked_ac
    - input_boolean.shabbat_timers_shaked
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.shaked_ac

- control:
    - binary_sensor.shabbat_roei_ac
    - input_boolean.shabbat_timers_roei
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.roei_ac

- control:
    - binary_sensor.shabbat_maayan_ac
    - input_boolean.shabbat_timers_maayan
  condition: [group.shabbat_timers_in_effect]
  action: climate
  entities:
    - climate.maayan_ac

- control: [binary_sensor.shabbat_middle_floor_hallway]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.middle_floor_hallway_lights

- control:
    - binary_sensor.shabbat_master_bedroom_light
    - input_boolean.shabbat_timers_master_bedroom
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.master_bedroom_spot_lights
    - light.master_bedroom_curtain_light
    - light.amit_night_light
    - light.shiri_night_light

- control:
    - binary_sensor.shabbat_master_bedroom_windows
    - input_boolean.shabbat_timers_master_bedroom
  condition: [group.shabbat_timers_in_effect]
  action: cover
  entities:
    - cover.master_bedroom_north_window
    - cover.master_bedroom_west_window

- control:
    - binary_sensor.shabbat_master_bedroom_bathroom
    - input_boolean.shabbat_timers_master_bedroom
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.master_bedroom_bathroom_lights
    - light.master_bathroom_mirror_lights

- control:
    - input_boolean.shabbat_walk_in_clothet_lights
    - input_boolean.shabbat_timers_master_bedroom
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.walk_in_closet

- control:
    - binary_sensor.shabbat_shaked_lights
    - input_boolean.shabbat_timers_shaked
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.shaked_main_light

- control:
    - binary_sensor.shabbat_shaked_windows
    - input_boolean.shabbat_timers_shaked
  condition: [group.shabbat_timers_in_effect]
  action: cover
  entities:
    - cover.shaked_north_window
    - cover.shaked_south_window

- control: [input_boolean.shabbat_timers_shaked]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.shaked_bathroom_lights

- control:
    - binary_sensor.shabbat_maayan_lights
    - input_boolean.shabbat_timers_maayan
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.maayan_room_main_lights

- control: [input_boolean.shabbat_timers_maayan]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.maayan_bathroom_lights

- control: [input_boolean.shabbat_timers_reut]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities:
    - light.reut_bathroom_lights

- control: [input_boolean.shabbat_timers_roei]
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities: [light.roei_bathroom_lights]

- control: [binary_sensor.coatroom_venta_schedule]
  action: switch
  entities: [switch.coatroom_venta]

- control: [binary_sensor.watering_system]
  # condition: [binary_sensor.watering_required]
  action: switch
  entities: [switch.irrigation]

- control: [binary_sensor.upper_floor_buffet_light_schedule]
  action: light
  entities: [light.upper_floor_buffet]

- control: [binary_sensor.front_yard_entrance_lights]
  condition: [binary_sensor.not_shabbat_timers_in_effect]
  action: light
  entities:
    - light.front_yard_lights
    - light.surrounding_up_down_lights

- control:
    - input_boolean.shabbat_reut_main_light
    - input_boolean.shabbat_timers_reut
  condition: [group.shabbat_timers_in_effect]
  action: light
  entities: [light.reut_room_main_lights]

- control: [binary_sensor.synagogue_shabbat]
  condition: [binary_sensor.jewish_calendar_issur_melacha_in_effect]
  action: sensibo
  entities:
    - climate.drvm_ymyn_m_rb
    - climate.drvm_shml_mzrkh
    - climate.m_rb_ymyn_tspvn_knysh
    # - climate.m_rb_shml_drvm
    - climate.mzgn_tspvn

- control: [binary_sensor.synagogue_erev_shabbat]
  condition:
    - binary_sensor.jewish_calendar_erev_shabbat_hag
    - binary_sensor.synagogue_erev_shabbat
  action: sensibo
  entities:
    - climate.drvm_ymyn_m_rb
    - climate.drvm_shml_mzrkh
    - climate.m_rb_ymyn_tspvn_knysh
    # - climate.m_rb_shml_drvm
    - climate.mzgn_tspvn
