- id: evening-lights
  alias: lights on every evening
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  condition:
    - condition: state
      entity_id: group.shabbat_timers_in_effect_main_floor
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.entrance_lights
    
- id: evening-windows
  alias: close windows every night
  trigger:
    platform: sun
    event: sunset
    offset: '03:00:00'
  condition:
    - condition: state
      entity_id: group.shabbat_timers_in_effect_main_floor
      state: 'off'
  action:
    service: cover.close_cover
    entity_id: 
      - cover.living_room_windows
      - cover.dinning_room_windows

- id: midnight
  alias: lights off and close windows every midnight
  trigger:
    platform: time
    at: '00:00:00'
  condition:
    - condition: state
      entity_id: group.shabbat_timers_in_effect_main_floor
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.entrance_lights
        - switch.living_room_lights
        - switch.living_room_peripheral_lights
    - service: cover.close_cover
      entity_id: 
        - cover.living_room_windows
        - cover.dinning_room_windows

- id: shabbat-starts
  alias: setup house when Shabbat starts
  trigger:
    platform: state
    entity_id: group.shabbat_timers_in_effect
    from: 'off'
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.living_room_lights
        - switch.living_room_peripheral_lights
    - service: switch.turn_off
      entity_id: 
        - switch.master_bedroom_smart_toilet
    - service: media_player.turn_off
      entity_id: 
        - media_player.nestmini9591
        - media_player.amit_s_echo_dot
        
- id: shabbat-ends
  alias: setup house when Shabbat ends
  trigger:
    platform: state
    entity_id: group.shabbat_timers_in_effect
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.hot_plate
        - switch.master_bedroom_ac
        - switch.reut_ac
        - switch.shaked_ac
        - switch.roei_ac
        - switch.master_bedroom_smart_toilet
