- id: evening-lights
  alias: lights on every evening
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
    service: switch.turn_on
    entity_id: switch.shelly_shsw_pm_766cbe # entrance light
    
- id: evening-windows
  alias: close windows every night
  trigger:
    platform: sun
    event: sunset
    offset: '03:00:00'
  action:
    service: cover.close_cover
    entity_id: 
      - cover.shelly_shsw_25_b92fd1
      - cover.shelly_shsw_25_68c63af981be

- id: midnight
  alias: lists off and close windows every midnight
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.shelly_shsw_pm_766cbe
        - switch.shelly_shsw_25_68c63af91b61_1 # living room lights
        - switch.shelly_shsw_25_68c63af91b61_2 # living room peripheral
    - service: cover.close_cover
      entity_id: 
        - cover.shelly_shsw_25_b92fd1
        - cover.shelly_shsw_25_68c63af981be

- id: shabbat-starts
  alias: setup house when Shabbat starts
  trigger:
    platform: state
    entity_id: group.shabbat_timers_in_effect
    from: 'off'
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.shelly_shsw_pm_766cbe
        - switch.shelly_shsw_pm_766477 # master bedroom light
        - switch.shelly_shsw_25_68c63af91b61_1
        - switch.shelly_shsw_25_68c63af91b61_2
    - service: cover.open_cover
      entity_id: 
        - cover.shelly_shsw_25_b92fd1
        - cover.shelly_shsw_25_68c63af981be
    - service: media_player.turn_off
      entity_id: 
        - media_player.nestmini9591
        - media_player.amit_s_echo_dot
